### PR TITLE
Make maintainable

### LINKED ISSUE #1: use better typing in modules/network
The network module rely heavily on tuples list and dict, it should probably define it's own more specific types to make the code easier to read and maintain

### PR DESCRIPTION
**Pull request by trinity-1686a**
heavy rewrite of the ipset part
all but `networkd.py` has been tested

fix #1

### CODE REVIEW

**Comment by darkgallium** [comment]
I tested it successfully except the get_user_info part.

The introduction of a user class in managed.py is problematic since the daemon then serializes the user object using pickle, we would also need to import this User class in the django part. (because currently, when deserializing on the django part, it says `ModuleNotFoundError: No module named 'managed'`) Importing the user class would (1) probably cause confusion with django's user classes and (2) will break the separation between langate2000 and langate2000-netcontrol. 

We may discuss that but I'm more in favour of keeping the old system with lists, since it's simpler.

**Comment by trinity-1686a** [comment]
How about having a `to_dict()`/`from_dict()`? Having classes makes it way more easier to navigate imo, old structs made types highly complex (`List[Tuple[time, Dict[str, Tuple[int, int]]]]`), and likely not maintainable

**Comment by darkgallium** [comment]
Agreed, navigation is way simpler in the new version using the User class.
I wrote a to_dict() method for the User class and now it works.

**Review by darkgallium — COMMENTED** [review]
Go 4 it !

**Pull request merged**
